### ISSUE TITLE
how to use your library to build my camera path

### ISSUE THREAD

**Issue by syjzwjj** [cjgammon/three.js-camera-path-tool#1]
Hello Recently I found your library on github and I don't know how to build my camera path use your code? can you describe your usage more detailed ？ thank you

**Comment by cjgammon** [comment]
Hi, so this project is a crude little tool for building out camera paths of a scene visually.  Using the key commands in the Readme you can add a path segment (with "=").  You can drag and drop Three.js formatted JSON models into the page to load them.  I have part of a video that shows it in use on youtube: https://youtu.be/RETNfk_odhQ?t=31m54s .  If you hit the question mark button it brings up a menu that has a save button which will save out the data for the camera path.  I believe there are some examples of camera paths being used in the three.js samples if you need an example of that.

**Comment by syjzwjj** [comment]
wow! I see your video ! It's really an amazing and cool library ! And it seems like your library can cut down the computation of camera orbit ! It realy give me some ideas ! Thank you !
